package com.fuma.hiselectors.selectors.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.fuma.hiselectors.application.model.Application;
import com.fuma.hiselectors.selectors.model.Selectors;
import com.fuma.hiselectors.selectors.model.SelectorsSnsAccount;
import jakarta.persistence.EntityManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.UUID;
import org.hibernate.SessionFactory;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.junit.jupiter.api.Test;
import org.springframework.data.jpa.repository.support.JpaRepositoryFactory;
import org.springframework.orm.jpa.SharedEntityManagerCreator;

class SelectorsSnsAccountRepositoryQueryTest {

    @Test
    void findsNonDeletedAccountsForGenerationInIdOrder() throws Exception {
        String databaseName = "selectors_sns_account_query_"
                + UUID.randomUUID().toString().replace("-", "");
        String jdbcUrl = "jdbc:h2:mem:" + databaseName;

        try (Connection keeperConnection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            createSchema(keeperConnection);
            seedRows(keeperConnection);

            StandardServiceRegistry serviceRegistry = new StandardServiceRegistryBuilder()
                    .applySetting("jakarta.persistence.jdbc.driver", "org.h2.Driver")
                    .applySetting("jakarta.persistence.jdbc.url", jdbcUrl)
                    .applySetting("jakarta.persistence.jdbc.user", "sa")
                    .applySetting("jakarta.persistence.jdbc.password", "")
                    .applySetting("hibernate.hbm2ddl.auto", "validate")
                    .applySetting("hibernate.show_sql", "false")
                    .build();
            try {
                try (SessionFactory sessionFactory = new MetadataSources(serviceRegistry)
                        .addAnnotatedClass(Application.class)
                        .addAnnotatedClass(Selectors.class)
                        .addAnnotatedClass(SelectorsSnsAccount.class)
                        .buildMetadata()
                        .buildSessionFactory()) {
                    EntityManager sharedEntityManager = SharedEntityManagerCreator
                            .createSharedEntityManager(sessionFactory);
                    SelectorsSnsAccountRepository repository = new JpaRepositoryFactory(
                            sharedEntityManager).getRepository(
                            SelectorsSnsAccountRepository.class);

                    assertThat(repository.findAllForGenerationOrderByIdAsc(10L))
                            .extracting(SelectorsSnsAccount::getId)
                            .containsExactly(10L, 30L);
                }
            } finally {
                StandardServiceRegistryBuilder.destroy(serviceRegistry);
            }
        }
    }

    private void createSchema(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table application (
                        application_id bigint generated by default as identity primary key,
                        user_id bigint not null,
                        generation_id bigint not null,
                        sns_code enum ('YOUTUBE', 'INSTAGRAM') not null,
                        sns_account_id varchar(200) not null,
                        follower_count bigint,
                        last_content_at timestamp,
                        engagement_rate numeric(5, 2),
                        alarm_yn boolean not null,
                        policy_agreed_at timestamp not null,
                        status enum ('PENDING', 'APPROVED', 'REJECTED') not null,
                        created_at timestamp,
                        updated_at timestamp,
                        constraint uq_application_user_generation
                            unique (user_id, generation_id)
                    )
                    """);
            statement.execute("""
                    create table selectors (
                        selectors_id bigint generated by default as identity primary key,
                        application_id bigint,
                        user_id bigint,
                        selectors_role_id varchar(20) not null,
                        selectors_code varchar(20),
                        selectors_nickname varchar(20),
                        created_at timestamp,
                        updated_at timestamp
                    )
                    """);
            statement.execute("""
                    create table selectors_sns_account (
                        selectors_sns_account_id bigint
                            generated by default as identity primary key,
                        selectors_id bigint not null,
                        sns_code enum ('YOUTUBE', 'INSTAGRAM'),
                        account_id varchar(100),
                        follower_count bigint,
                        is_deleted boolean not null,
                        last_collected_at timestamp,
                        profile_image_url varchar(500),
                        created_at timestamp,
                        updated_at timestamp
                    )
                    """);
        }
    }

    private void seedRows(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    insert into application (
                        application_id, user_id, generation_id, sns_code, sns_account_id,
                        alarm_yn, policy_agreed_at, status
                    ) values
                        (100, 1, 10, 'INSTAGRAM', 'generation-10', false,
                            timestamp '2026-08-01 00:00:00', 'APPROVED'),
                        (200, 2, 20, 'YOUTUBE', 'generation-20', false,
                            timestamp '2026-08-01 00:00:00', 'APPROVED')
                    """);
            statement.executeUpdate("""
                    insert into selectors (
                        selectors_id, application_id, user_id, selectors_role_id
                    ) values
                        (101, 100, 1, 'MEMBER'),
                        (102, 100, 3, 'MEMBER'),
                        (201, 200, 2, 'MEMBER')
                    """);
            statement.executeUpdate("""
                    insert into selectors_sns_account (
                        selectors_sns_account_id, selectors_id, sns_code, account_id, is_deleted
                    ) values
                        (30, 101, 'INSTAGRAM', 'generation-10-later-id', false),
                        (5, 201, 'YOUTUBE', 'other-generation', false),
                        (20, 101, 'INSTAGRAM', 'deleted', true),
                        (10, 102, 'INSTAGRAM', 'generation-10-earlier-id', false)
                    """);
        }
    }
}
