package com.fuma.hiselectors.creator.discovery;

import static org.assertj.core.api.Assertions.assertThat;

import com.fuma.hiselectors.creator.discovery.BrandScoreCalculator.BrandScore;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class BrandScoreCalculatorTest {

    private final BrandScoreCalculator calculator = new BrandScoreCalculator();

    @Test
    @DisplayName("실측 - '공식 유튜브 채널' 표현을 잡는다")
    void detectsOfficialChannelPhrase() {
        BrandScore score = calculator.calculate(
                "Disney Korea", "월트디즈니 컴퍼니 코리아 공식 유튜브 채널입니다.", null);

        assertThat(score.isBrand()).isTrue();
        assertThat(score.hits()).isNotEmpty();
    }

    @Test
    @DisplayName("채널명에 '공식' 이 있으면 브랜드로 본다")
    void officialInTitleIsBrand() {
        BrandScore score = calculator.calculate("무신사 공식채널", "신상품 소식을 전합니다.", null);

        assertThat(score.isBrand()).isTrue();
    }

    @Test
    @DisplayName("IG 핸들에 official 이 들어간 개인 크리에이터는 브랜드가 아니다")
    void handleContainingOfficialIsNotBrand() {
        // 핸들을 지우지 않고 검사하면 이 크리에이터가 통째로 걸러진다
        BrandScore score = calculator.calculate(
                "다욧언니",
                "다이어트 브이로그 채널\n인스타 : dietunni_official",
                "dietunni_official");

        assertThat(score.isBrand()).isFalse();
        assertThat(score.score()).isZero();
    }

    @Test
    @DisplayName("실측 - '- Topic' 자동 생성 채널은 발굴 대상이 아니다")
    void autoGeneratedTopicChannelIsExcluded() {
        BrandScore score = calculator.calculate("ILLIT - Topic",
                "Provided to YouTube by ...", null);

        assertThat(score.isBrand()).isTrue();
        assertThat(score.hits()).contains("자동 생성 채널(- Topic)");
    }

    @Test
    @DisplayName("설명에만 약한 신호가 하나 있으면 브랜드로 보지 않는다")
    void singleWeakHintInBodyIsNotEnough() {
        BrandScore score = calculator.calculate(
                "코스민", "여러 브랜드와 협업했습니다", null);

        assertThat(score.score()).isEqualTo(1);
        assertThat(score.isBrand()).isFalse();
    }

    @Test
    @DisplayName("일반 크리에이터는 0점이다")
    void ordinaryCreatorScoresZero() {
        BrandScore score = calculator.calculate(
                "핏지피티 홈트", "매일 10분 홈트레이닝 루틴을 올립니다.", "fitgpt_daily");

        assertThat(score.score()).isZero();
        assertThat(score.hitsAsText()).isNull();
    }

    @Test
    @DisplayName("판정 근거는 컬럼 길이(200자)를 넘지 않는다")
    void hitsTextIsTruncated() {
        BrandScore score = calculator.calculate(
                "공식 주식회사 브랜드 뉴스 엔터테인먼트 본사 고객센터 official",
                "공식 채널 주식회사 브랜드 뉴스 엔터테인먼트", null);

        assertThat(score.hitsAsText()).hasSizeLessThanOrEqualTo(200);
    }

    @Test
    @DisplayName("null 입력도 예외 없이 처리한다")
    void handlesNullInput() {
        BrandScore score = calculator.calculate(null, null, null);

        assertThat(score.score()).isZero();
        assertThat(score.isBrand()).isFalse();
    }
}
