package com.fuma.hiselectors.inspection.model;

public enum ViolationTypeCode {
    AD_DISCLOSURE_INVALID,
    AFFILIATE_LINK_INVALID,
    ABUSIVE_LANGUAGE,
    HATE_DISCRIMINATION,
    VIOLENCE_THREAT,
    SEXUAL_CONTENT,
    POLITICAL_CONTENT,
    SOCIAL_CONTROVERSY,
    FALSE_EXAGGERATED_CLAIM,
    BRAND_REPUTATION_DAMAGE
}
